# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'extoDockerConnection'
  imageRepository: 'meghanaksgowda/meghawebapp'
  imageTag: '$(Build.BuildId)'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build Docker Image'
    pool:
      name: default
    steps:
    - task: Docker@2
      displayName: 'Build an image'
      inputs:
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(imageRepository):$(imageTag)

  - job: Push
    displayName: 'Push Docker Image to Docker Hub'
    pool:
      name: default
    steps:
    - task: Docker@2
      displayName: 'Push an image'
      inputs:
        command: 'push'
        repository: '$(imageRepository):$(imageTag)'






